name: unit_test_quick

on:
  push:
    branches-ignore:
      - master

  pull_request:
    branches-ignore:
      - master

  workflow_dispatch: # Enable workflow to be run manually.

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Pun pytest
        run: poetry run pytest --cov=./ --cov-report=xml

      - name: Publish to Codecov
        uses: codecov/codecov-action@v1.3.2
