name: unit_test_full

on:
  pull_request:
    branches:
      - main

  workflow_dispatch: # Enable workflow to be run manually.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10"]
        exclude:
          - os: windows-latest
            python-version: "3.10"
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Run pytest
        run: poetry run pytest --cov=./ --cov-report=xml

      - name: Publish to Codecov
        uses: codecov/codecov-action@v1.3.2
